### ISSUE TITLE
Where is the "Guided Generation" code?

### ISSUE THREAD

**Issue by Suxyuuu** [javirandor/passgpt#1]
According to your paper, the model should be able to generate passwords guided by rules/templates. However, I don't find this part of codes in this repository.

**Comment by javirandor** [comment]
Hi! I have just uploaded a [notebook](https://github.com/javirandor/passgpt/blob/main/notebooks/Guided%20Password%20Generation.ipynb) with an example of guided generation. Unfortunately, I do not have any script that allows you to do this at scale; you can adapt the code if needed.
